version: '3.8'

volumes:
  postgis_data:

services:
  service_area_backend:
    image: alexanderditzend/service_area_backend:latest
    deploy:
      placement:
        constraints:
          - node.labels.postgis == 1
    ports:
      - 55174:8000
    environment:
      - SECRET_KEY = ${DJANGO_SECRET_KEY}
      - DB_NAME = ${DB_NAME}
      - DB_USER = ${DB_USER}
      - DB_PASSWORD = ${DB_PASSWORD}
      - DB_HOST = ${DB_HOST}
      - DB_PORT = ${DB_PORT}
      - ALLOWED_HOSTS = ${ALLOWED_HOSTS}
  postgis:
    image: postgis/postgis
    deploy:
      placement:
        constraints:
          - node.labels.postgis == 1
    ports:
      - 35164:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--locale=en_US.UTF-8
      - PGDATA=/var/lib/postgresql/data