# Generated by Django 3.2.13 on 2022-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French')], default='English', max_length=20)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pounds'), ('USD', 'US Dollars')], default='USD', max_length=20)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
