# Generated by Django 3.2.13 on 2022-06-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='polygon',
            new_name='geo_json_polygon',
        ),
    ]
